manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pointing
      remote: petejohanson
      revision: main     # Enth√§lt die notwendigen Glidepoint-Treiber
    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: main #new entry
      
  self:
    path: config
